# Site settings
title: Your awesome title
email: your-email@domain.com
baseurl: "/bg" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
